### ISSUE TITLE
Recurring matplotlib warning 

### ISSUE THREAD

**Issue by gianmatharu** [PrincetonUniversity/seisflows#23]
```
/usr/local/lib/python2.7/dist-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
```

This warning occurs when using wrappers to spawn multiple processes pbsdsh/slurm (presumably). Reloading objects that import obspy causes this warning to trigger on each import. At the very least it creates spam in the output.log; it's unclear if there is additional overhead. 

https://github.com/matplotlib/matplotlib/issues/5836 - relevant matplotlib discussion. 

Would be nice to suppress this or perhaps limit importing Obspy to where necessary.

**Comment by rmodrak** [comment]
These kinds of issues led me to avoid obspy in writing an early prototype of SeisFlows.  I remember  a very similar warning then.  Through system wide settings, I believe our system administrator was able to something to fix it.

**Comment by rmodrak** [comment]
Currently, obspy is imported at module level only once, in ``seisflows.preprocess.base``. A module level import seems appropriate in this case because the main work of the module (i/o and signal processing) rests entirely on obspy calls.

As a workaround, perhaps you could suppress warnings by adding some code at the end of ``seisflows.tools.config`` (but don't commit these changes to the master branch). This page I think provides a recipe:
http://stackoverflow.com/questions/14463277/how-to-disable-python-warnings

Since ``seisflows.tools.config`` is always imported prior to any other SeisFlows modules, add coding here should reliably suppress warnings.

If you decide to try this approach and it proves successful, could you post an update to this thread?

Thanks,
Ryan

**Comment by gianmatharu** [comment]
This warning seems to have disappeared without any effort on my part so I'll close this for now.

**Comment by rmodrak** [comment]
glad to hear
